<?php
return [
    'filepicker' => [
        'accepted_file_types' => 'image/*,audio/*,video/*,application/pdf',
        'placeholder_line1' => 'Choose files or drag and drop to upload',
        'placeholder_line2' => '%s up to %s',
        'can_browse' => true,
        'can_drop' => true,
        'validate_file_size' => true,
        'base64' => false,
        'base64_output' => 'url',
        'show_credits' => false,
        'auto_upload' => false,
        'max_files' => 1,
        'max_file_size' => '5mb',
        'max_total_file_size' => null,
        'add_new_files_to' => 'top',
        'max_file_size_exceeded_label' => 'File is too large',
        'max_file_size_label' => 'Maximum file size is {filesize}',
        'max_total_file_size_exceeded_label' => 'Maximum total file size exceeded',
        'max_total_file_size_label' => 'Maximum total file size is {filesize}',
        'invalid_file_type_label' => 'Wrong file type uploaded',
        'expected_file_types_label' => 'Only {allButLastType} and {lastType} files allowed',
        'show_image_preview' => true,
        'can_resize_image' => false,
        'image_resize_width' => null,
        'image_resize_height' => null,
        'can_crop' => false,
        'crop_aspect_ratio' => '16:9',
    ],
];
